title: Awesome KGEM Surveys and Benchmarks
description: >
  An awesome list of KGEM surveys and benchmarking studies for link prediction.

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
