title: KGEM Meta-Review of Surveys and Benchmarks
description: >
  A meta-review of KGEM surveys and benchmarking studies for link prediction.

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
